### ISSUE TITLE
PHP 8.2 dynamic property deprecations

### ISSUE THREAD

**Issue by NicoBR333** [Rehike/Rehike#255]
```
Deprecated:
Creation of dynamic property Rehike\Model\Masthead\MNotificationClickcard::$content is deprecated
C:\xampp\htdocs\models\Masthead\MMasthead.php:314
Deprecated: PlayerInfo.php:68 Creation of dynamic property Rehike\Player\PlayerInfo::$embedJsUrl is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\ContinuationWrapper::$_browse_continuation is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\ContinuationTypeWrapper::$_append_continuation is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\ContinuationTypeWrapper::$_reload_continuation is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuation::$_reload_action is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuation::$_append_action is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationWrapper::$_target_id is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationAction::$_timing_alt is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationActionTiming::$_a is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationActionTiming::$_b is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationActionTiming::$_a is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationActionTiming::$_b is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationReloadAction::$_a is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationAppendAction::$_a is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\ContinuationTypeWrapper::$_append_continuation is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\ContinuationTypeWrapper::$_reload_continuation is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\BrowseContinuationWrapper::$_target_id is deprecated
Deprecated: Message.php:152 Creation of dynamic property Com\Google\Protos\Youtube\Api\Innertube\ContinuationWrapper::$_browse_cont
```

**Comment by YukisCoffee** [comment]
This is a known issue with PHP 8.2, we've just been slow to fix it. Could you elaborate at all on the problems you're experiencing other than that?

**Comment by NicoBR333** [comment]
The reply works, but won't show up until you refresh the page or click to hide and show
But nothing else other than that

**Comment by YukisCoffee** [comment]
I believe that's actually a Hitchhiker issue then, it was YouTube's fault and not ours lol. Will keep open until the PHP 8.2 bug is fixed tho

**Comment by aubymori** [comment]
Edited issue title and content to better reflect the actual issue here.

**Comment by NicoBR333** [comment]
Nope, it still happens here... Probably some kind of issue on hosting or similar... Probably not happening to someone else. I'm using the latest PHP build and it seems that Fiddler can have some issues after running for 10 hours
![image](https://user-images.githubusercontent.com/77538136/221298094-e8969dc0-570c-4f89-bb28-31cbdba56ded.png)

**Comment by aubymori** [comment]
UPDATE REHIKE

**Comment by YukisCoffee** [comment]
> it seems that Fiddler can have some issues after running for 10 hours

We have chosen to stop supporting Fiddler due to this very reason. We no longer use it internally and aren't experienced enough to safely provide information on it. [Read here for more information about the preferred installation method.](https://github.com/Rehike/Rehike/issues/226)
